import { ContextMode, UserContext } from './types';

export const CONTEXT_PRESETS: Record<ContextMode, UserContext> = {
  deep_work: {
    mode: 'deep_work',
    activeApp: 'VS Code',
    activity: 'Deep work / coding',
    meeting: false,
    deadlineMinutes: 18,
    attentionBudgetRemaining: 65,
    interruptionsToday: 14,
    recentInterruptions: 2,
    customRules: ['Silently suppress low-priority banter', 'Batch pull requests'],
  },
  studying: {
    mode: 'studying',
    activeApp: 'Obsidian & Browser',
    activity: 'Studying Distributed Systems',
    meeting: false,
    deadlineMinutes: 45,
    attentionBudgetRemaining: 75,
    interruptionsToday: 4,
    recentInterruptions: 0,
    customRules: ['Allow academic deadline notices', 'Suppress social channels'],
  },
  meeting: {
    mode: 'meeting',
    activeApp: 'Zoom / Google Meet',
    activity: 'Executive Sprint Planning',
    meeting: true,
    deadlineMinutes: undefined,
    attentionBudgetRemaining: 30,
    interruptionsToday: 18,
    recentInterruptions: 5,
    customRules: ['Strict silence except P0 outages', 'Never interrupt during active mic'],
  },
  gaming: {
    mode: 'gaming',
    activeApp: 'Steam / Fullscreen Game',
    activity: 'Competitive Matchmaking',
    meeting: false,
    deadlineMinutes: undefined,
    attentionBudgetRemaining: 20,
    interruptionsToday: 2,
    recentInterruptions: 0,
    customRules: ['Suppress work pings', 'Allow emergency household alerts'],
  },
  idle: {
    mode: 'idle',
    activeApp: 'Finder / Desktop',
    activity: 'Coffee Break / Away from keyboard',
    meeting: false,
    deadlineMinutes: undefined,
    attentionBudgetRemaining: 95,
    interruptionsToday: 1,
    recentInterruptions: 0,
    customRules: ['Show all reasonable updates soon', 'Normal interruption threshold'],
  },
};
